'use client';

import { useMemo, useState } from 'react';

type Recipe = { name:string; slot:string; profile:string; mood:string; use:string; wb:string; aperture:string; exposure:string; recipe:string[]; image:number; tone:string };
const stills: Recipe[] = [
 {name:'Kodachrome 64',slot:'MR1',profile:'PP1',mood:'Punchy slide',use:'Bright days · color · travel',wb:'5400K · A +0.25',aperture:'f/4',exposure:'Meter normally',image:0,tone:'#e4482f',recipe:['Cine2 · Pro','Black −2 · BG Narrow −3','Sat +10 · Phase 0','R+4 G+2 B+5 C+3 M+1 Y−2']},
 {name:'Tri-X 400',slot:'C1 / PP menu',profile:'PP2',mood:'Gritty monochrome',use:'Street · hard light · texture',wb:'5500K · preview only',aperture:'Any',exposure:'Protect highlights',image:1,tone:'#a0a0a0',recipe:['Cine2 · B&W','Black −4 · BG Narrow −4','Crispening +7 for bite','Add grain in post']},
 {name:'Vibrant Arizona',slot:'M2',profile:'PP3',mood:'Pastel desert',use:'Architecture · desert · playful color',wb:'5600K · A+1 M+0.5',aperture:'f/5.6',exposure:'Meter normally',image:2,tone:'#db8f77',recipe:['S-Cinetone · S-Cinetone','Black +2 · BG Wide +3','Sat +6 · Phase +1','R+2 G−1 B+1 C+1 M+2 Y+3']},
 {name:'Pacific Blues',slot:'M1',profile:'PP4',mood:'Cool coastal',use:'Ocean · sky · clean daylight',wb:'6500K · B+1.5 G+0.5',aperture:'f/5.6',exposure:'Check faces',image:3,tone:'#4da3cf',recipe:['Cine2 · Pro','Black 0 · BG Wide +2','Sat +7 · Phase −2','R0 G−1 B+5 C+4 M−1 Y−2']},
 {name:'Reggie’s Portra',slot:'MR3',profile:'PP5',mood:'Warm soft portrait',use:'People · daylight · everyday',wb:'AWB White · A+2',aperture:'f/2.5',exposure:'−⅓ to −½ EV',image:4,tone:'#c39161',recipe:['Movie · S-Cinetone','Black −5 · BG Wide −7','Knee 90% +3 · Sat −3 · Phase +2','R0 G+7 B+2 C+5 M+3 Y+1']},
 {name:'California Summer',slot:'M3',profile:'PP6',mood:'Warm nostalgic',use:'Golden light · street · vacations',wb:'6500K · A+1.5',aperture:'f/4',exposure:'Ease A to +1 for skin',image:5,tone:'#d29a49',recipe:['S-Cinetone · Pro','Black 0 · BG Wide +2','Sat +9 · Phase +1','R+3 G0 B−2 C−1 M+1 Y+4']},
 {name:'Portra 800',slot:'MR2',profile:'PP10',mood:'Moody portrait',use:'Indoor · evening · mixed light',wb:'4800K · A+2 M+1',aperture:'f/2.5',exposure:'Keep ISO ≤ 6400',image:6,tone:'#ae7061',recipe:['S-Cinetone · Pro','Black −2 · BG Middle 0','Knee manual ~90% · Sat +12 · Phase +3','R+3 G+5 B+5 C+7 M+7 Y−3']},
 {name:'Vintage Kodachrome',slot:'M4',profile:'PP1',mood:'Faded retro',use:'Road trips · snapshots · nostalgia',wb:'5650K · B+0.5 M+0.5',aperture:'f/4',exposure:'+0.3 EV optional',image:7,tone:'#a3a77e',recipe:['Same PP1 as MR1','Different WB creates aged-slide cast','Clean version remains on MR1','Card slot: restore after format']},
];
const movies=[
 {slot:'MR1',look:'D’Amore',profile:'PPLUT1',aperture:'f/2.5–2.8',note:'Warm skin · daily driver'}, {slot:'MR2',look:'s709',profile:'PPLUT4',aperture:'f/2.8–4',note:'Neutral baseline · trust zebras'}, {slot:'MR3',look:'S-Cinetone',profile:'PP11',aperture:'f/2.5',note:'Soft portrait · no LUT dependency'}, {slot:'M1',look:'Look 2',profile:'PPLUT3',aperture:'f/2.5–2.8',note:'Warm + punchy'}, {slot:'M2',look:'Look 1',profile:'PPLUT2',aperture:'f/2.8–4',note:'Neutral · filmic · environmental'}, {slot:'M3',look:'Cine (flat)',profile:'Cine4',aperture:'f/2.8–4',note:'Grade later · Log OFF · ±0 EV'}
];
export default function Home(){
 const [tab,setTab]=useState<'stills'|'movie'|'setup'>('stills'); const [query,setQuery]=useState(''); const [open,setOpen]=useState<string|null>('Kodachrome 64');
 const filtered=useMemo(()=>stills.filter(r=>`${r.name} ${r.mood} ${r.use} ${r.slot}`.toLowerCase().includes(query.toLowerCase())),[query]);
 return <main><header className="topbar"><div className="brand"><span className="eyebrow">FIELD GUIDE / A7C II</span><h1>Looks, in your pocket.</h1><p>40mm f/2.5 G · ready-to-shoot recipes</p></div><div className="status"><span/> STILL / A</div></header>
 <nav className="tabs" aria-label="Guide sections">{(['stills','movie','setup'] as const).map(t=><button key={t} onClick={()=>setTab(t)} className={tab===t?'active':''}>{t==='stills'?'Photo looks':t==='movie'?'Movie bank':'Quick setup'}</button>)}</nav>
 {tab==='stills'&&<section className="content"><div className="section-head"><div><span className="kicker">STILL BANK · 8 LOOKS</span><h2>Choose the feeling.</h2></div><label className="search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search mood, scene, slot…" aria-label="Search recipes"/></label></div><div className="grid">{filtered.map(r=><article className={`card ${open===r.name?'expanded':''}`} key={r.name} style={{'--tone':r.tone} as React.CSSProperties}><button className="card-main" onClick={()=>setOpen(open===r.name?null:r.name)} aria-expanded={open===r.name}><div className="photo" style={{backgroundImage:"url('/images/looks-contact-sheet.png')",backgroundSize:'400% 200%',backgroundPosition:`${(r.image%4)*33.333}% ${r.image>3?100:0}%`}}><span className="slot">{r.slot}</span><span className="profile">{r.profile}</span></div><div className="card-copy"><div><p className="mood">{r.mood}</p><h3>{r.name}</h3><p className="use">{r.use}</p></div><span className="chev">⌄</span></div><div className="quick"><div><span>WB</span><strong>{r.wb}</strong></div><div><span>LENS</span><strong>{r.aperture}</strong></div><div><span>EXPOSURE</span><strong>{r.exposure}</strong></div></div></button><div className="details"><p className="detail-label">PROFILE BUILD</p>{r.recipe.map((x,i)=><div className="detail-row" key={x}><span>{String(i+1).padStart(2,'0')}</span><p>{x}</p></div>)}</div></article>)}</div><aside className="tip"><b>Remember</b><p>White balance is stored in the memory slot, not the Picture Profile. Recall the slot and shoot—don’t reset WB afterward.</p></aside></section>}
 {tab==='movie'&&<section className="content"><div className="section-head"><div><span className="kicker">MOVIE BANK · MANUAL EXPOSURE</span><h2>Motion, mapped.</h2></div></div><div className="movie-hero"><div><span>180° SHUTTER</span><strong>24p → 1/50</strong><strong>30p → 1/60</strong><strong>60p → 1/125</strong></div><p>Neutral WB on PPLUT looks. Zebras 100+ clip / ~94 skin highlight. Detail −7. Auto ISO ceiling 6400.</p></div><div className="movie-list">{movies.map(m=><article key={m.slot}><span className="movie-slot">{m.slot}</span><div><h3>{m.look}</h3><p>{m.note}</p></div><div><span>{m.profile}</span><b>{m.aperture}</b></div></article>)}</div><aside className="tip warning"><b>Baked means baked</b><p>PPLUT color cannot be recovered later. Nail exposure and neutral white balance at capture.</p></aside></section>}
 {tab==='setup'&&<section className="content"><div className="section-head"><div><span className="kicker">BEFORE YOU WALK OUT</span><h2>Sixty-second setup.</h2></div></div><ol className="steps"><li><span>01</span><div><h3>Set the complete camera state</h3><p>PP + WB + aperture + Auto ISO + drive + Eye AF + metering.</p></div></li><li><span>02</span><div><h3>Save the memory</h3><p>MENU → Shooting → Camera Set. Memory → choose slot → confirm.</p></div></li><li><span>03</span><div><h3>Know what survives</h3><p>MR1–3 are internal and format-proof. M1–M4 live on the card and are wiped on format.</p></div></li><li><span>04</span><div><h3>Keep Tri-X one press away</h3><p>Assign Picture Profile to C1 or Fn; PP2 is intentionally outside the memory bank.</p></div></li></ol><div className="registers"><span>CUSTOM WB REGISTERS</span><p><b>① Pacific Blues</b> 6500K B+1.5 G+0.5</p><p><b>② Portra 800</b> 4800K A+2 M+1</p><p><b>③ Vibrant Arizona</b> 5600K A+1 M+0.5</p></div></section>}
 <footer>SONY A7C II · PERSONAL FIELD REFERENCE <span>Values are tuned starting points—check skin and skies.</span></footer></main>
}
